config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  get "admin" => 'admin/homes#top'
  get 'admin_ranking' => "admin/posts#ranking"
  namespace :admin do
  resources :users, only:[:index, :show] do
    collection do
      get 'search'
  end
end
  resources :posts, only:[:index, :show, :destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only:[:create, :destroy]
    collection do
      get 'search'
  end
  end
  resources :pets, only:[:index, :show, :destroy] do
   collection do
      get 'search'
  end
end
  end

  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'ranking' => "user/posts#ranking"
  get "about" => "user/homes#about"
  root 'user/homes#top'
  scope module: 'user' do
  resources :posts, only:[:new, :show, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
   resources :comments, only:[:create, :destroy]
   resources :tags
   collection do
      get 'search'
  end
end
  resources :users, only:[:show, :update, :edit, :index] do
     collection do
      get 'search'
  end
end
  resources :pets, only:[:new, :show, :index, :create, :update, :edit] do
   collection do
      get 'search'
  end
end
end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  attachment :pet_image
  
  validates :Animal_name, presence: true

  def self.search(keyword)
    where(["Animal_name like?", "%#{keyword}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
    validates :owner_name, :pet_kind, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :user
  attachment :profile_image
  
end

app/controllers/admin/pets_controller.rb
class Admin::PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to admin_pets_path
  end

  def search
    if params[:keyword].present?
      @pets = Pet.where('Animal_name LIKE ?',"%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @pets = Pet.all
    end
  end


  layout 'admin'

  private

  def pet_params
    params.require(:pet).permit(:Animal_name, :introduction, :pet_image, :food, :hobby, :tool, :user_id, :caution)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController


  def index
    @users = User.page(params[:page]).order(id:"ASC")
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def search
    if params[:keyword].present?
      @users = User.where('owner_name LIKE ?',"%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @users = Usere.all
    end
  end

  layout 'admin'

  private

  def user_params
   params.require(:user).permit(:owner_name, :profile_image, :pet_kind, :introduction)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to post_path(post)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
     @posts = Post.page(params[:page]).reverse_order
     @tag_lists = Tag.all
     @posts = @posts.where('title LIKE ?', "%#{params[:search]}%")if params[:search].present?
     @page = 10
  end
  
  def about
  end

end

app/controllers/user/pets_controller.rb
class User::PetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def new
    @pet = Pet.new
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def index
    @pets = Pet.all
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    @pet.save
    redirect_to pet_path(@pet.id)
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet.id)
  end

  def search
    if params[:keyword].present?
      @pets = Pet.where('Animal_name LIKE ?',"%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @pets = Pet.all
    end
  end


  private

  def pet_params
    params.require(:pet).permit(:Animal_name, :introduction, :pet_image, :food, :hobby, :tool, :user_id, :caution)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(",")
    if @post.save
       @post.save_posts(tag_list)
       redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @post_tags = @post.tags
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def search
    @tag_lists = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.all
  end

  def ranking
    @posts = Post.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @page = 10
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :video)
  end

end

app/controllers/user/tags_controller.rb
class User::TagsController < ApplicationController
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def index
    @users = User.page(params[:page]).reverse_order
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to user_path(@user.id)
  end

   def search
    if params[:keyword].present?
      @users = User.where('owner_name LIKE ?',"%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @users = User.all
    end
  end

  private

  def user_params
   params.require(:user).permit(:owner_name, :profile_image, :pet_kind, :introduction)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/pets_helper.rb
module Admin::PetsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/views/user/pets/edit.html.erb
 <div class= "continer">
  <div class="col-6 mx-auto">
   <h4>みんなのペット図鑑</h4>
    <%= form_with model:@pet, local:true do |f| %>
    <%= attachment_image_tag @pet, :pet_image, :fill, 100, 100, fallback: "no_image.jpg", size: '100x100' %>
    <%= f.attachment_field :pet_image %>
    <table class="table table-hover table-inverse">
     <tr>
      <th>ペットの種類</th>
      <td><%= f.text_field :Animal_name, class:"w-100", autofocus: true, id:"inputIntroduction" %></td>
     </tr>
     <tr>
      <th>ペットの種類</th>
      <td><%= f.text_field :introduction, class:"w-100", autofocus: true, id:"inputIntroduction" %></td>
     </tr>
     <tr>
      <th>主食・おやつ</th>
      <td><%= f.text_field :food, class:"w-100",  autofocus: true, id:"inputFood" %></td>
     </tr>
     <tr>
      <th>習性・すきなこと</th>
      <td><%= f.text_area :hobby, class:"w-100",  autofocus: true, id:"inputHobby" %></td>
     </tr>
     <tr>
      <th>おすすめの飼育用品</th>
      <td><%= f.text_field :tool, class:"w-100",  autofocus: true, id:"inputTool" %></td>
     </tr>
     <tr>
      <th>飼育で大変なこと</th>
      <td><%= f.text_area :caution, class:"w-100",  autofocus: true, id:"inputCaution"  %></td>
     </tr>
    </table>

    <button class="btn btn-outline-success", tape="submit">変更を保存する</button>
   <% end %>
  </div>
 </div>

app/views/user/pets/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h4>みんなのペット図鑑</h4>
   <div>
    <%= form_with url: search_pets_path, local: true, method: :get do |form| %>
    <%= form.text_field :keyword %>
    <button class="btn btn-secondary", type="submit">検索</button>
    <% end %>
   </div>

   <div>
    <%= link_to new_pet_path do %>
    <button class="btn btn-primary">ペットを追加</button>
    <% end %>
   </div>


   <h5>投稿一覧</h5>
   <table class="table table-hover table-inverse table-sm">
    <tr>
     <th></th>
     <th>ペットの種類</th>
     <th>最終更新日時</th>
     <th></th>
    </tr>
    <% @pets.each do |pets| %>
    <tr>
     <td><%= attachment_image_tag pets, :pet_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100' %></td>
     <td>
      <%= link_to pet_path(pets) do %>
      <%= pets.Animal_name %>
      <% end %>
     </td>
     <td><%= pets.updated_at.strftime('%Y/%m/%d') %></td>
     <td></td>
    </tr>
    <% end %>
   </table>
  </div>
 </div> 
</div>
 

app/views/user/pets/new.html.erb
<div class= "continer">
 <div class="col-6 mx-auto">
  <h4>みんなのペット図鑑</h4>
  <h5>投稿ページ</h5>
  <%= form_with model:@pet, local:true do |f| %>
   <h4>画像</h4>
   <%= f.attachment_field :pet_image %>

   <h4>ペットの種類(犬・ハムスター等)</h4>
   <%= f.text_field :Animal_name %>

   <h4>どんな動物？</h4>
   <%= f.text_field :introduction %>

   <h4>主食・おやつ</h4>
   <%= f.text_field :food %>

   <h4>おすすめの飼育用具(おもちゃ・ケージ等)</h4>
   <%= f.text_field :tool %>

   <h4>習性・すきなこと</h4>
   <%= f.text_field :hobby %>

   <h4>飼育で大変なこと</h4>
   <%= f.text_field :caution %>

   <%= f.submit "新規投稿" %>
  <% end %>
 </div>
</div>

app/views/user/pets/search.html.erb
<div class= "continer">
 <div class="col-6 mx-auto">
  <table>
   <tr>
    <th></th>
    <th>検索結果</th>
   </tr>
   <% @pets.each do |pet| %>
   <tr>
    <td>
     <%= link_to pet_path(pet.id) do %>
     <%= attachment_image_tag pet, :pet_image, :fill, 200, 150, format: 'jpeg', fallback: "no_image.jpeg", size: "200x150" %>
     <% end %>
    <td>
    <td><%= pet.Animal_name %></td>
   </tr>
   <% end %>
  </table>
 </div>
</div>

app/views/user/pets/show.html.erb
<div class= "continer">
 <div class="col-6 mx-auto">

  <h4>みんなのペット図鑑</h4>

  <table class="table table-hover table-inverse table-sm">
   <tr>
    <th><%= attachment_image_tag @pet, :pet_image, :fill, 200, 150, format: 'jpeg', fallback: "no_image.jpg", size: "200x150" %></td>
   </tr>
   <tr>
    <th>名前</th>
    </tr>
   <tr>
    <td><%= @pet.Animal_name %></td>
   </tr>
   <tr>
    <th>どんな動物？</th>
   </tr>
   <tr>
    <td><%= @pet.introduction %></td>
   </tr>
   <tr>
    <th>主食・おやつ</th>
   </tr>
   <tr>
    <td><%= @pet.food %></td>
   </tr>
   <tr>
    <th>習性・すきなこと</th>
   </tr>
   <tr>
    <td><%= @pet.hobby %></td>
   </tr>
   <tr>
    <th>飼育上大変なこと</th>
   </tr>
   <tr>
    <td><%= @pet.caution %></td>
   </tr>
   <tr>
    <th>おすすめの飼育道具</th>
   </tr>
   <tr>
    <td><%= @pet.tool %></td>
   </tr>
  </table>
 <div>
  <%= link_to edit_pet_path(@pet) do %>
  <button class="btn btn-primary">編集する</button>
  <% end %>
 </div>
</div>
</div>