config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  get "admin" => 'admin/homes#top'
  get 'admin_ranking' => "admin/posts#ranking"
  namespace :admin do
  resources :users, only:[:index, :show] do
    collection do
      get 'search'
  end
end
  resources :posts, only:[:index, :show, :destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only:[:create, :destroy]
    collection do
      get 'search'
  end
  end
  resources :pets, only:[:index, :show, :destroy] do
   collection do
      get 'search'
  end
end
  end

  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'ranking' => "user/posts#ranking"
  get "about" => "user/homes#about"
  root 'user/homes#top'
  scope module: 'user' do
  resources :posts, only:[:new, :show, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
   resources :comments, only:[:create, :destroy]
   resources :tags
   collection do
      get 'search'
  end
end
  resources :users, only:[:show, :update, :edit, :index] do
     collection do
      get 'search'
  end
end
  resources :pets, only:[:new, :show, :index, :create, :update, :edit] do
   collection do
      get 'search'
  end
end
end
end

app/models/admin.rb
class Admin < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  attachment :pet_image
  
  validates :Animal_name, presence: true

  def self.search(keyword)
    where(["Animal_name like?", "%#{keyword}%"])
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title,  presence: true
  has_one_attached :video

  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def save_posts(tags)
   current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
   old_tags = current_tags - tags
   new_tags = tags - current_tags

   old_tags.each do |old_name|
     self.tags.delete Tag.find_by(tag_name:old_name)
   end

   new_tags.each do |new_name|
     post_tag = Tag.find_or_create_by(tag_name:new_name)
     self.tags << post_tag
   end
 end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_maps, dependent: :destroy
  has_many :posts, through: :tag_maps

def self.search(keyword)
    where(["tag_name like?", "%#{keyword}%"])
  end
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :owner_name, :pet_kind, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :user
  attachment :profile_image
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @posts = Post.page(params[:page]).reverse_order
     @tag_lists = Tag.all
     @posts = @posts.where('title LIKE ?', "%#{params[:search]}%")if params[:search].present?
     @page = 10
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_path
  end

  def about
  end

  layout 'admin'

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path(resource)
    when User
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:owner_name, :pet_kind, :email, :profile_image])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
     @posts = Post.page(params[:page]).reverse_order
     @tag_lists = Tag.all
     @posts = @posts.where('title LIKE ?', "%#{params[:search]}%")if params[:search].present?
     @page = 10
  end
  
  def about
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/pets_helper.rb
module Admin::PetsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/pets_helper.rb
module User::PetsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/tags_helper.rb
module User::TagsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/homes/about.html.erb
<div class="container">
 <div class="row">
  <h5 class="px-3 mx-auto">
  こんにちは！<br>
  ここでは皆さんのペット自慢ができます！<br>
  かわいい瞬間の動画や写真を投稿してください。<br>
  会員登録をしなくても投稿一覧は見れますが、<br>
  コメントやいいねを残すことはできません。
  </h5>
 </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">

 <h3>みんなの投稿</h3>
  <div>
   <h4>タグ一覧</h4>
    <% @tag_lists.each do |list| %>
     <%= link_to search_posts_path(tag_id: list.id) do %>
      <%= list.tag_name %>
      <%= "(#{list.posts.count})" %>
     <% end %>
    <% end %>
  </div>
 <h4>投稿一覧</h4>
  <table class="table table-hover table-inverse table-sm">
   <tr>
    <th>タイトル</th>
    <th></th>
    <th>ユーザー名</th>
    <th>コメント</th>
    <th>いいね</th>
   </tr>
   <% @posts.each do |post| %>
    <tr>
     <td>
      <%= link_to admin_post_path(post) do %>
      <%= post.title %>
      <% end %>
     </td>
     <td><%= attachment_image_tag post, :image, :fill, 70, 70, format: 'jpeg' %>
      <% if post.video.attached? %>
       <video src="<%= rails_blob_path(post.video) %>"width="70" height="70"type="video/mp4" controls></video>
      <% end %>
     </td>
     <td>
      <%= link_to admin_user_path(post.user) do %>
      <%= attachment_image_tag post.user, :profile_image, :fill, 70,70, format: 'jpeg',fallback: "no_image.jpg" %><br>
      <% end %>
      <%= post.user.owner_name %>
     </td>
     <td><%= link_to "コメント#{post.comments.count}件", admin_post_path(post.id) %></td>
     <td>
      <%= "★#{post.favorites.count}" %>
     </td>
     <td>
      <%= link_to admin_post_path(post), method: :delete do %>
      <button class="btn btn-danger">削除</button>
      <% end %>
     </td>
    <% end %>
   </table>
  </div>
 </div>

 <%= paginate @posts %>